POST http://localhost:5000/api/users/register HTTP/1.1
Content-Type: application/json

{
    "credentials":{
        "email":"example@com.com",
        "password":"Qwerty1234!",
        "repeatedPassword":"Qwerty1234!"
    },
    "user_data":{
        "first_name":"John",
        "last_name":"Doe",
        "phone_number":123123123
    }
}

###

POST http://localhost:5000/api/auth HTTP/1.1
Content-Type: application/json

{
    "email":"example22@com.com",
    "password":"Qwerty1234!"
}
###
POST http://localhost:5000/api/auth HTTP/1.1
Content-Type: application/json

{
    "email":"example33@com.com",
    "password":"Qwerty1234!"
}
###
GET http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQzZDY5MGNjNjRmOGQyM2QwOWVkMGYiLCJpYXQiOjE2OTkwMTI0MTAsImV4cCI6MTY5OTYxNzIxMH0.1dooNaUHbeaDCxpBKGUHow0Ixfalt0ZT4Audh4KRZdg
###

GET http://localhost:5000/api/subscriptions/prices HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ1MmE4NDBiMDdlOWQ3YjBmMTFiNmEiLCJpYXQiOjE3MDAxMzg2NjQsImV4cCI6MTcwMDc0MzQ2NH0.WW3Fpsgh3b41zigo6HP2Qfy_12aFv1uk7s5Dlmze0Ic
###

POST http://localhost:5000/api/subscriptions/session HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTViYWM1YjY2Y2JjMjc4NjU0NTZhNWMiLCJpYXQiOjE3MDA1MDY3MjAsImV4cCI6MTcwMTExMTUyMH0.j4_XnfdvJd0W2NTWUqAK3UFQFiLhzZxho9g9SLBnHNE

{
    "priceId":"price_1OC534An9ZF4sVGm1A5YRzGh"
}

###
POST http://localhost:5000/api/subscriptions/cancel HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTU2NGQ5YjdmNTczNDVhZjg1NjU1ZTIiLCJpYXQiOjE3MDAxNTQ3OTYsImV4cCI6MTcwMDc1OTU5Nn0.MuBgrtScA1TKWRLbpXsJIYwYaqLOTooqSzZM0vx0pPQ

{
    "subscriptionId":"sub_1OD9hrAn9ZF4sVGmKTDPmiH7"
}


###
GET http://localhost:5000/api/subscriptions/prices?currency=pln HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQzZDY5MGNjNjRmOGQyM2QwOWVkMGYiLCJpYXQiOjE2OTkwMTI0MTAsImV4cCI6MTY5OTYxNzIxMH0.1dooNaUHbeaDCxpBKGUHow0Ixfalt0ZT4Audh4KRZdg
###

GET http://localhost:5000/api/subscriptions/ HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQzZDY5MGNjNjRmOGQyM2QwOWVkMGYiLCJpYXQiOjE2OTkxMTQ2MjUsImV4cCI6MTY5OTcxOTQyNX0.lupXiV1C3wy07CMyux5lA5Q_4aW-tvRQ-VloJGPO9UI
###
POST http://localhost:5000/api/subsciptions/sharing/join HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTU3Y2NmN2ZjZWI5ZjczYzkzMzFiZjciLCJpYXQiOjE3MDAzODI2NDcsImV4cCI6MTcwMDk4NzQ0N30.rmKIOkntR4vCjVX4Z4lC6_kux47dj7EeVoouT1wbg2c
POST http://localhost:5000/api/subsciptions/sharing/join HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTU3Y2NmN2ZjZWI5ZjczYzkzMzFiZjciLCJpYXQiOjE3MDAzODI2NDcsImV4cCI6MTcwMDk4NzQ0N30.rmKIOkntR4vCjVX4Z4lC6_kux47dj7EeVoouT1wbg2c
Content-Type: application/json

{
    "shareCode":246004138
}
###

GET http://localhost:5000/api/subsciptions/sharing/code HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTU3Y2NmN2ZjZWI5ZjczYzkzMzFiZjciLCJpYXQiOjE3MDAzODI2NDcsImV4cCI6MTcwMDk4NzQ0N30.rmKIOkntR4vCjVX4Z4lC6_kux47dj7EeVoouT1wbg2c
Content-Type: application/json
###
POST  http://localhost:5000/api/watchlists/655f9a6382947eb6fb5c9142 HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTVhNTQ4YjYyM2I4ZjNkOTc0N2E4MjUiLCJpYXQiOjE3MDA3NjE2OTMsImV4cCI6MTcwMTM2NjQ5M30.9FUxF6lskheA4XNC1KCjyuyzmdz3T2-RBaiBbk9sLQ8
Content-Type: application/json
###
DELETE  http://localhost:5000/api/watchlists/654793fce94b9d7aff14a1ac HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQzZDY5MGNjNjRmOGQyM2QwOWVkMGYiLCJpYXQiOjE2OTkxOTc5MDQsImV4cCI6MTY5OTgwMjcwNH0.rte-23Amurvk_TslT4EXKgle0AOILgaMJFXJwDZRkFU
Content-Type: application/json
###
GET  http://localhost:5000/api/watchlists/ HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTVkOWMzNWFkY2NmNTljNDE0NWEwNzkiLCJpYXQiOjE3MDA2NTc2MjUsImV4cCI6MTcwMTI2MjQyNX0.cPbWvy1LIEFP4xY7NuxOM7z9gqSXzUZtDlGv3ubdp5A
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTVhNTQ4YjYyM2I4ZjNkOTc0N2E4MjUiLCJpYXQiOjE3MDA3NjE2OTMsImV4cCI6MTcwMTM2NjQ5M30.9FUxF6lskheA4XNC1KCjyuyzmdz3T2-RBaiBbk9sLQ8
Content-Type: application/json
###
GET  http://localhost:5000/api/series/ HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTVhNTQ4YjYyM2I4ZjNkOTc0N2E4MjUiLCJpYXQiOjE3MDA3NjE2OTMsImV4cCI6MTcwMTM2NjQ5M30.9FUxF6lskheA4XNC1KCjyuyzmdz3T2-RBaiBbk9sLQ8
Content-Type: application/json
###
POST  http://localhost:5000/api/genres/ HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQzZDY5MGNjNjRmOGQyM2QwOWVkMGYiLCJpYXQiOjE2OTkxOTc5MDQsImV4cCI6MTY5OTgwMjcwNH0.rte-23Amurvk_TslT4EXKgle0AOILgaMJFXJwDZRkFU
Content-Type: application/json

{
    "genre":"horror"
}
###
POST  http://localhost:5000/api/genres/testmultiple HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQzZDY5MGNjNjRmOGQyM2QwOWVkMGYiLCJpYXQiOjE2OTkxOTc5MDQsImV4cCI6MTY5OTgwMjcwNH0.rte-23Amurvk_TslT4EXKgle0AOILgaMJFXJwDZRkFU
Content-Type: application/json

{
    "genre":["horror","fantasy","rpg","fps","romans"]
}
###

GET http://localhost:5000/api/series/655fbb9cd11b214f6db65e80 HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTVhNTQ4YjYyM2I4ZjNkOTc0N2E4MjUiLCJpYXQiOjE3MDA3NjE2OTMsImV4cCI6MTcwMTM2NjQ5M30.9FUxF6lskheA4XNC1KCjyuyzmdz3T2-RBaiBbk9sLQ8
Content-Type: application/json
###

###
GET http://localhost:5000/api/subscriptions/ HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTVkOWMzNWFkY2NmNTljNDE0NWEwNzkiLCJpYXQiOjE3MDA2MzY3NzMsImV4cCI6MTcwMTI0MTU3M30.i9JqWwv4BNQnZtmSTl5lpZ8btUdcqUMRjIVyXmSaGK0
Content-Type: application/json
###
GET http://localhost:5000/api/subscriptions/subscriptionCheck
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTVhNTQ4YjYyM2I4ZjNkOTc0N2E4MjUiLCJpYXQiOjE3MDA1ODAyODcsImV4cCI6MTcwMTE4NTA4N30.4J1H-xxoyR2vHItsPqwoxAYXtkv8piRf7qqXRy91NxQ