POST http://localhost:5000/api/users/register HTTP/1.1
Content-Type: application/json

{
    "credentials":{
        "email":"example@com.com",
        "password":"Qwerty1234!",
        "repeatedPassword":"Qwerty1234!"
    },
    "user_data":{
        "first_name":"John",
        "last_name":"Doe",
        "phone_number":123123123
    }
}

###

POST http://localhost:5000/api/auth HTTP/1.1
Content-Type: application/json

{
    "email":"example@com.com",
    "password":"Qwerty1234!"
}
###
POST http://localhost:5000/api/auth HTTP/1.1
Content-Type: application/json

{
    "email":"example33@com.com",
    "password":"Qwerty1234!"
}
###
GET http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQzZDY5MGNjNjRmOGQyM2QwOWVkMGYiLCJpYXQiOjE2OTkwMTI0MTAsImV4cCI6MTY5OTYxNzIxMH0.1dooNaUHbeaDCxpBKGUHow0Ixfalt0ZT4Audh4KRZdg
###

GET http://localhost:5000/api/subscriptions/prices HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQzZDY5MGNjNjRmOGQyM2QwOWVkMGYiLCJpYXQiOjE2OTkxMTQ2MjUsImV4cCI6MTY5OTcxOTQyNX0.lupXiV1C3wy07CMyux5lA5Q_4aW-tvRQ-VloJGPO9UI
###

POST http://localhost:5000/api/subscriptions/session HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ1MmE4NDBiMDdlOWQ3YjBmMTFiNmEiLCJpYXQiOjE2OTkwMzE2OTMsImV4cCI6MTY5OTYzNjQ5M30.TWLA-OJY8SDNIQ_C2PBcg1At8wwjFbNkkxxNbTOct-Y

{
    "priceId":"price_1NzL8yAn9ZF4sVGmGfwLCtYu"
}

###
POST http://localhost:5000/api/subscriptions/cancel HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQzZDY5MGNjNjRmOGQyM2QwOWVkMGYiLCJpYXQiOjE2OTg5NDQ4NTcsImV4cCI6MTY5OTU0OTY1N30.rd8fGbA24_V966rBgt2zPswSGnu7POEz-Yidm1aXLrk

{
    "subscriptionId":"sub_1O85SSAn9ZF4sVGmnzvzXfVB"
}


###
GET http://localhost:5000/api/subscriptions/prices?currency=pln HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQzZDY5MGNjNjRmOGQyM2QwOWVkMGYiLCJpYXQiOjE2OTkwMTI0MTAsImV4cCI6MTY5OTYxNzIxMH0.1dooNaUHbeaDCxpBKGUHow0Ixfalt0ZT4Audh4KRZdg
###

GET http://localhost:5000/api/subscriptions/ HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQzZDY5MGNjNjRmOGQyM2QwOWVkMGYiLCJpYXQiOjE2OTkxMTQ2MjUsImV4cCI6MTY5OTcxOTQyNX0.lupXiV1C3wy07CMyux5lA5Q_4aW-tvRQ-VloJGPO9UI
###
POST http://localhost:5000/api/subscriptions/join HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQzZDY5MGNjNjRmOGQyM2QwOWVkMGYiLCJpYXQiOjE2OTkwMTI0MTAsImV4cCI6MTY5OTYxNzIxMH0.1dooNaUHbeaDCxpBKGUHow0Ixfalt0ZT4Audh4KRZdg
Content-Type: application/json

{
    "shareCode":246004138
}
###

POST http://localhost:5000/api/subscriptions/deactivate_share_code HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQzZDY5MGNjNjRmOGQyM2QwOWVkMGYiLCJpYXQiOjE2OTkwMTI0MTAsImV4cCI6MTY5OTYxNzIxMH0.1dooNaUHbeaDCxpBKGUHow0Ixfalt0ZT4Audh4KRZdg
Content-Type: application/json
###
POST  http://localhost:5000/api/watchlists/654793fce94b9d7aff14a1ac HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQzZDY5MGNjNjRmOGQyM2QwOWVkMGYiLCJpYXQiOjE2OTkxOTc5MDQsImV4cCI6MTY5OTgwMjcwNH0.rte-23Amurvk_TslT4EXKgle0AOILgaMJFXJwDZRkFU
Content-Type: application/json
###
DELETE  http://localhost:5000/api/watchlists/654793fce94b9d7aff14a1ac HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQzZDY5MGNjNjRmOGQyM2QwOWVkMGYiLCJpYXQiOjE2OTkxOTc5MDQsImV4cCI6MTY5OTgwMjcwNH0.rte-23Amurvk_TslT4EXKgle0AOILgaMJFXJwDZRkFU
Content-Type: application/json
###
GET  http://localhost:5000/api/watchlists/ HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQzZDY5MGNjNjRmOGQyM2QwOWVkMGYiLCJpYXQiOjE2OTkxOTc5MDQsImV4cCI6MTY5OTgwMjcwNH0.rte-23Amurvk_TslT4EXKgle0AOILgaMJFXJwDZRkFU
Content-Type: application/json